# -*- coding: utf-8 -*-
"""Classification Algorithm Recommendation Tool

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kMQ-Km4xrp4TroIb1wOhFjLWhYZffg-a

### **INSTALLATION**
"""

# Commented out IPython magic to ensure Python compatibility.
#@title Run this cell to get clone github
!git clone https://github.com/beyzanurarslan/classification-algorithm-recommendation.git
# %cd /content/classification-algorithm-recommendation

"""### **UPLOAD YOUR DATA FILE (csv, xlsx, xls)**"""

from google.colab import files
uploaded = files.upload()

"""### **GET YOUR RESULT**"""

#@title Write below your data file name and target column name
#@markdown 
data = "data.csv" #@param {type:"string"}
target_column_name = "target" #@param [] {allow-input: true}


!python main.py -data $data -y $target_column_name